name: plantenv_distributed
channels:
  - bioconda
  - conda-forge
dependencies:
  #3.10 needed for plantcv v3.14.3
  - python=3.11
  - jupyterlab
  - ipympl
  - pyarrow
  - openpyxl
  - pandarallel
  - swifter
  - dask-jobqueue
  - pip
  - pip:
    - plantcv==4.2.1
