name: plantenv_pcv3
channels:
  - bioconda
  - conda-forge
dependencies:
  #3.10 needed for plantcv v3.14.3
  - python=3.10
  - pip
  - pip:
    - plantcv==3.13.0
    - opencv-python
  #- anaconda::opencv
  #- conda-forge::plantcv